### PR TITLE
add skywalking 8 dockerfile.

### PR DESCRIPTION
**Pull request by JaredTan95**

### CODE REVIEW

**Comment by wu-sheng** [comment]
I will wait Gao for reviewing, as he could upload the imagr to dockerhub.

**Comment by JaredTan95** [comment]
Okay.

**Comment by wu-sheng** [comment]
If you want to upload, I think you need to open an Jira ticket. Infra team controls this.😀

**Review by hanahmily — APPROVED** [review]
LGTM

**Pull request merged**
