### PR TITLE
Increase JVM ES memory

### PR DESCRIPTION
**Pull request by w-a-n-g-s-h-u-n**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why increasw default memory?

**Comment by w-a-n-g-s-h-u-n** [comment]
It triggers frequent GC and OOM






------------------ 原始邮件 ------------------
发件人: "吴晟 Wu Sheng"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 上午9:51
收件人: "apache/skywalking-docker"<skywalking-docker@noreply.github.com>;
抄送: "汪顺"<731307020@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/skywalking-docker] Increase JVM ES memory (#4)




Why increasw default memory?

**Comment by w-a-n-g-s-h-u-n** [comment]
image
image

**Comment by hanahmily** [comment]
docker compose yamls intend to provide an example for users. @w-a-n-g-s-h-u-n for your scenario, `2gb` may be enough, well, it may not work for others though. So I suggest we just remove this env variable.

Would you please check it out when removing it?

**Comment by w-a-n-g-s-h-u-n** [comment]
@hanahmily Yes,you're right

**Pull request closed without merging**
