### PR TITLE
Activate the health module

### PR DESCRIPTION
**Pull request by rainbend**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
You need this on the compose?

**Comment by rainbend** [comment]
> You need this on the compose?

Health check need to be used https://github.com/apache/skywalking-docker/blob/master/8/8.2.0/compose/docker-compose.yml#L54

**Review by hanahmily — CHANGES_REQUESTED** [review]
From compose files in main repo, you need both of them:
```
SW_HEALTH_CHECKER: default
SW_TELEMETRY: prometheus
```

**Comment by rainbend** [comment]
> From compose files in main repo, you need both of them:
> 
> ```
> SW_HEALTH_CHECKER: default
> SW_TELEMETRY: prometheus
> ```

@hanahmily  Done, please review  :)

**Review by hanahmily — APPROVED** [review]
LGTM, thanks @arugal

**Pull request merged**
